/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_robert_tom_App */

#ifndef _Included_org_robert_tom_App
#define _Included_org_robert_tom_App
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_robert_tom_App
 * Method:    getSystemClockInTicks
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_robert_tom_App_getSystemClockInTicks
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
