/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JniSample */

#ifndef _Included_JniSample
#define _Included_JniSample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JniSample
 * Method:    sayHellofromC
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_JniSample_sayHellofromC
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
